#!/bin/sh

## have to add conf directory to pick up log4j config file
PHENOTE_CLASSPATH=classfiles:conf
for file in jars/*.jar; do 
  if [ $file != jars/phenote.jar ]; then 
    #echo "Adding ${file} to CLASSPATH"
    PHENOTE_CLASSPATH=${PHENOTE_CLASSPATH}:${file}; 
  fi;
done

echo "java -Xmx1000M -classpath ${PHENOTE_CLASSPATH} phenote.main.PhenotePlus $@"
java -Xmx10000M -classpath ${PHENOTE_CLASSPATH} phenote.main.PhenotePlus $@

##java -Xmx300M -classpath classfiles:jars/oboedit.jar:jars/org.geneontology.jar:jars/BrowserLauncher2-10rc4.jar:jars/junit-4.0.jar:jars/tomcat-servlet.jar:jars/xbean.jar:jars/jsr173_1.0_api.jar:jars/phenoxmlbeans.jar:jars/phenoteconfigbeans.jar:jars/log4j-1.2.13.jar:jars/te-common.jar phenote.main.Phenote $@
