#!/bin/sh

## have to add conf directory to pick up log4j config file
PHENOTE_CLASSPATH=classfiles:conf
for file in jars/*.jar; do 
  if [ $file != jars/phenote.jar ]; then 
    #echo "Adding ${file} to CLASSPATH"
    PHENOTE_CLASSPATH=${PHENOTE_CLASSPATH}:${file}; 
  fi;
done

echo "java -Xmx950M -classpath ${PHENOTE_CLASSPATH} phenote.main.PhenotePlus $@"
java -Xmx9500M -classpath ${PHENOTE_CLASSPATH} phenote.main.PhenotePlus $@
