#!/usr/local/bin/perl

use strict;
use Getopt::Long;

my $fields = '';
my $delimiter = "\t";
my $newline;
my $pred;
my @pre = ();
my @th;
my $border = 0;
my $tharg = "";
my $tdarg = "";
my $tblclass = "sortable";
my $tblid = "stats_table";
my $title = "OBO Ontology Statistics";
GetOptions("th|t=s@"=>\@th,
	   "delimiter|d=s"=>\$delimiter,
	   "newline=s"=>\$newline,
           "predicate|p=s"=>\$pred,
           "pre=s@"=>\@pre,
           "border=s"=>\$border,
           "tharg=s"=>\$tharg,
           "tdarg=s"=>\$tdarg,
           "tblclass|c=s"=>\$tblclass,
	  );
if ($newline) {
    $/ = $newline;
}
else {
    $newline = "\n";
}
$tharg = " $tharg" if $tharg;
$tdarg = " $tdarg" if $tdarg;
$delimiter = '\s+' if $delimiter eq 'ws';

print "<html>\n";
print "<head>\n";
print '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">',"\n";
print "<title>$title</title>\n";
print "<script src=\"js/sorttable.js\"/>\n";
print '<link href="stylesheet.css" rel="stylesheet" type="text/css" media="screen">',"\n";
print "</head>";
print "</body>";
print "<h2>OBO Ontologies: current statistics</h2>\n";
print "<p><a href=\"index.html\">parent page</a></p>\n";
print "<table border=\"$border\" class=\"$tblclass\" id=\"$tblid\">\n";
if (@th) {
    print "  <tr>\n";
    printf "%s\n",
      join('', map {"    <th$tharg>".pquote($_)."</th>\n"} @th);
    print "  </tr>\n";
}
while(<>) {
    chomp;
    print "  <tr>\n";
    my @fields = split(/$delimiter/, $_);
    printf "%s\n",
      join('', map {"    <td$tdarg>".pquote($_)."</td>\n"} @fields);
    print "  </tr>\n";
}
print "</table>\n";
print "</body>\n";
print "</html>\n";

sub pquote {
    my $s = shift;
    $s='' unless defined $s;
    $s =~ s/_/ /g;
    $s =~ s/\</\&lt;/g;
    $s;
}

__END__

=head1 NAME

=head1 SYNOPSIS


=head1 DESCRIPTION

=head2 ARGUMENTS

=over


=item d|delimiter

tab is the default

=item newline

\n is the default

=back

=cut

